### ISSUE TITLE
Add a copy link/share button on list of created invites

### ISSUE THREAD

**Issue by mogno-jelly** [Wizarrrr/wizarr#10]
This is just a quality of life suggestion in case you ever need to re-send a previously created invite.  I know the formatting is just wizarrdomain/j/invite but it'd be nice to just a button for it as the first row as a link icon or something (or maybe have it so just clicking on the invite row in general will copy the link excluding any clicking done on the "Action" column).

**Comment by mtthidoteu** [comment]
> This is just a quality of life suggestion in case you ever need to re-send a previously created invite. I know the formatting

Thanks for the suggestion!
Done! I've updated Wizarr with this new feature!
