### ISSUE TITLE
Feature Request: New account configuration

### ISSUE THREAD

**Issue by josopu** [Wizarrrr/wizarr#107]
It would be nice if when the account is created I can choose to disable Online Media Sources, set maximum quality, enable experimental features, etc...

**Comment by Rocknrolldoggie** [comment]
Max quality is a good one

**Comment by josopu** [comment]
When was it completed? Can't see the settings on the invites. Maybe `max quality` was done, but what about the ability to disable Online Media Sources?

**Comment by realashleybailey** [comment]
Feature requests are now put in at https://features.wizarr.dev
