### ISSUE TITLE
[IMPROVEMENT] add both plex and emby/jellyfin servers for multi invite

### ISSUE THREAD

**Issue by xfouloux** [Wizarrrr/wizarr#109]
Hello,

the tool only allows you to configure either plex or emby/jellyfin

It would be so much more powerfull for the the tool to let us configure servers (let say 1 plex and 1 emby and/or 1 jellyfin)
and then allow us to generate invitation to selected servers or all

In my case, i hoped this tool would help me generate invite for users to both my emby and plex server, i allow them all libraries too.

This would be a huge help =)

**Comment by jmqlol** [comment]
could also be very useful to configure multiple plex servers - I have 2 different plex instances for availability purposes

**Comment by realashleybailey** [comment]
I would recommend spinning up multiple Wizarr instances as a feature like this would require a lot of modification to the existing code logic, and it would only benefit the select few.
