### ISSUE TITLE
[FEATURE REQUEST]: Wizarr send email directly

### ISSUE THREAD

**Issue by H3brewHammer** [Wizarrrr/wizarr#113]
Would love to see ability to configure SMTP so we can just input the invitee's email into wizarr, and wizarr would then just have a default html email it sends with the invite code

**Comment by vp-en** [comment]
Major +1 for this 👍  Would love a SMTP option

**Comment by realashleybailey** [comment]
Definitely coming, we will be adding Mass Emailing functionality too
