### ISSUE TITLE
[FEATURE REQUEST]: Custom Jellyfin Options For Users

### ISSUE THREAD

**Issue by woliver99** [Wizarrrr/wizarr#119]
I want to be able to make the user enable to show up on the login screen without me having to enable it
![image](https://user-images.githubusercontent.com/40217511/235337406-9337648b-e0c9-4bdb-98d5-56ffbbe1803f.png)

**Comment by woliver99** [comment]
Hey, this was closed as completed but how can I utilize it?

**Comment by realashleybailey** [comment]
Feature requests have moved to https://features.wizarr.dev
