### ISSUE TITLE
Unraid support

### ISSUE THREAD

**Issue by trashdad** [Wizarrrr/wizarr#12]
Requesting an unraid container, or an unraid-friendly version posted to Docker Hub.

**Comment by mtthidoteu** [comment]
This is definitely Unraid friendly, just fill in stuff as you would for any container :)

**Comment by mtthidoteu** [comment]
I have requested to be added to the Unraid Community Apps! Will close when successfully added!

**Comment by mizz141** [comment]
It's on the Community apps, just installed it.

**Comment by trashdad** [comment]
> It's on the Community apps, just installed it.

Just approved today! thank you!

@mtthidoteu you can close this issue, it's been approved. Thank you!!
