### ISSUE TITLE
Authentik SSO

### ISSUE THREAD

**Issue by JohnDoe-dev-spec** [Wizarrrr/wizarr#13]
Hi,

I'm not sure if it's just me, but i have been trying to get Authentik to work with Wizarr. 

I copied the paths to whitelist but Authentik still would not work with the site. I tried another application and it worked first time. So i went and revisited the steps taken for Wizarr.

What the issue for me was that the following white list path;

/j*

When i took this out Authentik started working, when i put it back in, it stopped. So instead i changed the whitelist path for this to;

/j/*

And now everything appears to be playing ball, i haven't yet actually tested the full invite cycle with it yet though.

Just thought worth highlighting just in case.

Thanks

**Comment by mtthidoteu** [comment]
Ah right! Good to know! I will change that! Thanks very much! 
Feel free to reopen the issue if you still find it doesn't behave correctly!
