### ISSUE TITLE
[FEATURE REQUEST]: Option to subscribe to tautulli's newsletter

### ISSUE THREAD

**Issue by MiranoVerhoef** [Wizarrrr/wizarr#136]
I would love for it to be possible whenever a user accepts a invite from Wizarr they get a option to:

i would like a newsletter with new movies and series every friday at 5Pm "Checkbox"

https://github.com/Tautulli/Tautulli/wiki/Tautulli-API-Reference

Seems like the API would make it possible to read out members.

**Comment by sideh** [comment]
If this is possible it'd be a great addition to this feature. I like thie idea. :)
