### ISSUE TITLE
expired (unused) invite still allows signup

### ISSUE THREAD

**Issue by mogno-jelly** [Wizarrrr/wizarr#14]
Hello, I was curious to see what happens if I tried to join with an unused invite that has expired, so I tested it out.  The invite was still able to be used.

**Comment by mtthidoteu** [comment]
> Hello, I was curious to see what happens if I tried to join with an unused invite that has expired, so I tested it out. The invite was still able to be used.

Ah interesting! Do you mean an invite that has expired in time? thanks

**Comment by mogno-jelly** [comment]
> > Hello, I was curious to see what happens if I tried to join with an unused invite that has expired, so I tested it out. The invite was still able to be used.
> 
> Ah interesting! Do you mean an invite that has expired in time? thanks

Correct, the expiration date/time has passed.

**Comment by mtthidoteu** [comment]
Okay, indeed! Invitations were being checked by date and time but only if they had already been used by someone (which is kind of useless ahaha), just pushed out a fix!
Let me know if it is now behaving correctly for you? On my end seems to work!

**Comment by mogno-jelly** [comment]
My test link that expired ended up getting used so I'll have to create another one haha, but ty for addressing

**Comment by mtthidoteu** [comment]
> My test link that expired ended up getting used so I'll have to create another one haha, but ty for addressing

Okay ahah!
I've just double tested it and I'm confident it is fixed so I'll close the issue! Thanks very much for trying it out!
