### ISSUE TITLE
[Feature Request] Push new users to Ombi

### ISSUE THREAD

**Issue by ecapuano** [Wizarrrr/wizarr#178]
Ombi runs a daily user import job from Plex but this means a new Wizarr invited user can't get into Ombi on day 1. It would be awesome if Wizarr could push this new member to Ombi so that the new user can login to it right away.

If this would be better handled elsewhere (like Ombi), feel free to close the FR :)

**Comment by mtthidoteu** [comment]
There is an ombi integration already, you have to enter the ombi api key and it should automatically integrate it
