### ISSUE TITLE
[FEATUER REQUEST] Access by donation with pay what you want

### ISSUE THREAD

**Issue by Squizzy911** [Wizarrrr/wizarr#179]
Hey guys,

the feature is definitely controversial. Unfortunately, this is because it can be used for illegal premium services. But I would want to give my friends access and share the cost. But since I don't want to chase the whole thing, a donation option would be conceivable. If this is implemented as pay what you want, that would at least not be so interesting for resellers. The system should look here in a monthly rythmus whether a donation was received or not and accordingly set a deadline until the membership is closed.

whats your opinion on it?

**Comment by mtthidoteu** [comment]
Unfortunately this is not something that is currently planned. Although you could setup a donation page via the custom html ?
