### ISSUE TITLE
Change min and max password length

### ISSUE THREAD

**Issue by ShadaxTheWizard** [Wizarrrr/wizarr#18]
A suggestion to change the password requirements for inbuilt auth, 20 characters is far lower than what I would normally use.

![Screenshot_29](https://user-images.githubusercontent.com/61526953/190895311-15da0035-8eea-4647-8a5d-b9980d1b0761.png)

**Comment by mtthidoteu** [comment]
I have changed the limit to 40!

**Comment by Y0ngg4n** [comment]
@mtthidoteu maybe would be nice if it could be customizable via environment variables.
