### ISSUE TITLE
[BUG] Container stops after starting

### ISSUE THREAD

**Issue by christianmerges** [Wizarrrr/wizarr#187]
**Describe the bug**
When i setup a new Container with the docker yaml:
  wizarr:
    image: ghcr.io/wizarrrr/wizarr:v3-alpha
    user: 1000:1000
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      APP_URL: ##### #URL at which you will access and share (the url has bend removed)
      DISABLE_BUILTIN_AUTH: false #Set to true ONLY if you are using another auth provider (Authelia, Authentik, etc)
    volumes:
      - /mnt/flashnvme/docker/wizarr/data:/data #subfolder "database" exists and 1000:1000 owns /data + subdirs
    ports:
      - 5690:5690

**Logs**
If applicable, add logs to help explain your problem
```
ModuleNotFoundError: No module named 'run'
```

**Additional context**
It also doesn't work in the "latest" branch.

**Comment by realashleybailey** [comment]
thats strange, could you maybe attempt to run ```docker image rm ghcr.io/wizarrrr/wizarr:v3-alpha``` then use this compose script ```---
version: "3.5"
services:
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:v3-alpha
    ports:
      - 5690:5690
    volumes:
      - ./data:/data/database
    environment:
      - APP_URL=0.0.0.0:5690
      - DISABLE_BUILTIN_AUTH=false
      - TZ=Europe/London
    privileged: true```

**Comment by christianmerges** [comment]
is the priveleged tag really necessary? 
I had to do with force: docker image rm ghcr.io/wizarrrr/wizarr:v3-alpha --force

Then i did: docker image pull ghcr.io/wizarrrr/wizarr:v3-alpha

After starting the container, same problem.

Then tried with ur compose file just changed the path in the volume section. The container started and was able to create the data. Then i stopped the container and set the privileged flag to false. It was starting again and kept running. I was able to see the webinterface, but was showing 404 error. So i changed the branch to latest and then the webinterface loaded without any errors. I didn't setup the application yet, just wanted to give some instant feedback.

So it seems that running it as user 1000 is the problem?

**Comment by realashleybailey** [comment]
Sorry, privileged tag is not necessary, it is remanence from my testing.

The 404 issue is directly correlated to APP_URL not match the url your attempting to access Wizarr on, APP_URL also not require that you specify http:// or https://, only that you specify port if your not accessing through a proxy.

I believe the issue you may relate to file permission to Wizarr database and session files when using user 1000

**Comment by christianmerges** [comment]
Ok i put the fqdn only in the docker compose, and the 404 is gone. The is one more bug, let me know if u want me to make an extra issue for that:

communicating with plex in latest branch works with http://plex:32400, in the v3 branch it is not accapting using just a hostname. Works only with the public fqdn of plex. Would be great to have communication internally working.

**Comment by realashleybailey** [comment]
Anything related to V3 you can leave bug reports over at [https://github.com/Wizarrrr/wizarr/discussions/188](url), I will deffo have a look into that issue because communication should work inside a docker network. Thank you for letting me know :)

**Comment by christianmerges** [comment]
> 

Please edit the link it is not pointig to the destination it is showing in the post.

**Comment by realashleybailey** [comment]
Fixed
