### ISSUE TITLE
[Feature Request] Profile function

### ISSUE THREAD

**Issue by xiNeRoar** [Wizarrrr/wizarr#195]
Add profile function like the one in jfa-go with ombi and jellyseerr, which allows the admin to decide what kind of content the users can request and what library the users can access in jellyfin and plex.

**Comment by realashleybailey** [comment]
We already have library control, however Wizarr V3 will be getting content age rating control in the future.

**Comment by xiNeRoar** [comment]
> We already have library control, however Wizarr V3 will be getting content age rating control in the future.

May I know where can i find library control for jellyseerr and Ombi? I have tried several times but all I can see is full access to request media.....

**Comment by vp-en** [comment]
> We already have library control, however Wizarr V3 will be getting content age rating control in the future.

@realashleybailey The nice thing with jfa-go, is that the user profiles also includes the transcoding options of the profile you select. That makes it much easier managing who and who shouldn't have access to whatever type of transcoding :). That's at least what I use it for.



> > We already have library control, however Wizarr V3 will be getting content age rating control in the future.
> 
> May I know where can i find library control for jellyseerr and Ombi? I have tried several times but all I can see is full access to request media.....
> 
> How should i configure it in setup? ![image](https://user-images.githubusercontent.com/66216186/258100485-7f4589e7-c57a-488a-b5c3-df08fe8664b5.png)

You select the `Scan For Libraries` and then you can select what Libraries they should get access to.
