### ISSUE TITLE
[BUG] Plex user invited to Plex home has no libraries shared

### ISSUE THREAD

**Issue by christianmerges** [Wizarrrr/wizarr#203]
**Describe the bug**

When a user joins via a link which was created with "invite to plex home", the user gets an email from plex regarding joining to the plex home. Even after clicking the link, there are no libraries shared with this user.

**Comment by christianmerges** [comment]
Just noticed that the libraries were shared after waiting ten minutes. Why is it not happening directly?

**Comment by realashleybailey** [comment]
Often times Plex has delays in there backend, unfortunately there is nothing we can do to resolve this as it's an issue inside Plex, it's very frustrating, I am emphasise with you.
