### ISSUE TITLE
[HELP] The localhost with the port does not work for me.

### ISSUE THREAD

**Issue by DumberSoft** [Wizarrrr/wizarr#204]
Hello, excuse my ignorance but I have tried to put the Alpha 3 in Docker-compose but it does not work for me, I would like to know if there is another way to install it, when installing it I enter with the port localhost:5690 but it does not enter, any help please, best regards.

CONTAINER ID   IMAGE                                  COMMAND                  CREATED              STATUS                          PORTS     NAMES
3af07d4d1a66   ghcr.io/wizarrrr/wizarr:v3-alpha-vue   "sh -c 'nginx && gun…"   About a minute ago   Exited (3) About a minute ago             agitated_banach

**Comment by ogkimra** [comment]
Could you get it to work?

**Comment by realashleybailey** [comment]
Please use ghcr.io/wizarrrr/wizarr:v3-beta

**Comment by ogkimra** [comment]
> Please use ghcr.io/wizarrrr/wizarr:v3-beta

![image](https://github.com/Wizarrrr/wizarr/assets/32086892/b5d39158-2195-4330-88fc-daed6bd5a46e)
2.6 GB? 💀

**Comment by ogkimra** [comment]
![image](https://github.com/Wizarrrr/wizarr/assets/32086892/fde137a6-370b-46fe-8d90-4e24c8afb47e)
Wait I messed something, didn't I

**Comment by realashleybailey** [comment]
We have had some issues with dialing in the right Github Actions Workflow for building out images, we are also trying to get image sizes down aswell

**Comment by realashleybailey** [comment]
This is fixed in the latest `ghcr.io/wizarrrr/wizarr:latest` build
