### ISSUE TITLE
[BUG] Invite Code can only contain uppercase letters.

### ISSUE THREAD

**Issue by clemone210** [Wizarrrr/wizarr#210]
**Describe the bug**
When creating a new invite code and using a numeric number, it will show that the code can only contain uppercase letters.

**Screenshots**
![Screenshot 2023_10_05 00-25-18@2x](https://github.com/Wizarrrr/wizarr/assets/43761260/3380a8c1-9cd7-447c-8e56-3535e48c3eec)

**Comment by mtthidoteu** [comment]
Currently the invite string can only contain letters (and no numbers).

**Comment by clemone210** [comment]
> Currently the invite string can only contain letters (and no numbers). 

The invitation code works. At least it saved it and I can open it from a different device.

Pls note I am referring to the beta v3 version.

**Comment by realashleybailey** [comment]
This was resolved thankfully a couple updates ago, so invites can accept numbers now as well as letters, the field is forced to uppercase for all letters so that people don't mistake lowercase and uppercase for invite codes

> > Currently the invite string can only contain letters (and no numbers).
> 
> The invitation code works. At least it saved it and I can open it from a different device.
> 
> Pls note I am referring to the beta v3 version.
