### ISSUE TITLE
[BUG] Invitations grants access to all libraries despite setting libraries manually

### ISSUE THREAD

**Issue by source011** [Wizarrrr/wizarr#211]
**Describe the bug**
Users invited gets access to all Jellyfin libraries even though manually chosen under advanced settings. Also the libraries chosen for the user is listed with their ID's and not the name in the invited page.

**Comment by realashleybailey** [comment]
You can manually select "Libraries" under "Advanced Options" when creating an invite :)

**Comment by source011** [comment]
Read my post again, that is what I meant. It doesn’t matter if I choose libraries manually, it grants access to every library anyway.

**Comment by realashleybailey** [comment]
Could you go to Settings -> Media Server -> Scan Libraries and reselect your Libraries you want and then reattempt, see if the issue persists.
