### ISSUE TITLE
launch error on vps running arm oracle

### ISSUE THREAD

**Issue by thinhplust** [Wizarrrr/wizarr#225]
exec /bin/sh: exec format error
exec /bin/sh: exec format error
exec /bin/sh: exec format error

I'm running it on oracle's vps running arm cpu and it gives me the error exec /bin/sh: exec format error
exec /bin/sh: exec format error
exec /bin/sh: exec format error.
I used the v2 version normally before.

Please fix it for me

**Comment by Squizzy911** [comment]
Same here

**Comment by realashleybailey** [comment]
This issue is being actively worked on, we face lots of issues when attempting to build on ARM, some systems work some don't so its more or less a "get lucky" situation when using ARM. Hopefully we can solve this.

**Comment by realashleybailey** [comment]
Yh thats fine, next update will have migration support for V2 to V3, we are just holding off until we resolve this ARM issue :)

**Comment by realashleybailey** [comment]
This issue is now resolved
