### ISSUE TITLE
a Couple of things noticed :-)

### ISSUE THREAD

**Issue by Nexius2** [Wizarrrr/wizarr#235]
Hello, I found some things not working or to check.

not sure if it's you directly but:
- the unraid container name could be changed to wiarr :-)
-the unraid icon path isn't ok, should be https://raw.githubusercontent.com/Wizarrrr/wizarr/master/frontend/src/assets/img/wizard.png

in the app:
- while adding the Server Name Display, we can't put name with "-" 
- it would be nice to have the server / library / expiration in the user panel without having to check per user

maybe normal for now:
- in the user management panel it only displays username and mail, no functions are available or displayed
- how does the multi server support works? 

great app !

**Comment by realashleybailey** [comment]
Multi Server support is under "Whats to Come", it hasnt been implemented yet, your feature requests could you put up on https://features.wizarr.dev, unraid support will come soon as of right now its really only there for testing and such
