### ISSUE TITLE
Creating an invitation generates a link to the local ip

### ISSUE THREAD

**Issue by RebeliusGaming** [wizarrrr/wizarr#244]
Hi. 
I'm just trying wizarr for the first time. It looks really cool!

I configured everything, but when trying to generate an invitation code, it links to my local ip address, eventhoug I configured the plex server information with my domain address.
![image](https://github.com/Wizarrrr/wizarr/assets/94674848/7730574a-3ace-4d1c-9bdb-70ff589d325e)

**Comment by realashleybailey** [comment]
Yes you would need to configure Wizarr behind a reverse proxy to make it available on a domain
