### ISSUE TITLE
User creation both fails and succeeds (jellyfin)

### ISSUE THREAD

**Issue by vandie** [Wizarrrr/wizarr#253]
Getting a strange issue at user creation with a valid invite that causes the user sign up to both succeed and fail. This leads to the user not being shown the followup pages
![CleanShot 2023-10-13 at 10 34 15@2x](https://github.com/Wizarrrr/wizarr/assets/9092863/63a0ce82-86e7-4370-883b-b991b39c41c4)
![CleanShot 2023-10-13 at 10 34 46@2x](https://github.com/Wizarrrr/wizarr/assets/9092863/e66c06b1-5edd-456e-9bf5-57fb96a17c73)
You have to rescan for users in the dashboard for this user to show up and the email shows up as not existing.
![CleanShot 2023-10-13 at 10 35 12@2x](https://github.com/Wizarrrr/wizarr/assets/9092863/6a91f3f4-3ff0-4026-b042-5c969ed4dd31)

When looking at the console. Only one request seems to fail, that being the settings file [here](
https://cdn.segment.com/v1/projects/rAjFFBAQf10L1mwRl4MlwDVYBYLcRdGY/settings)

I'm not seeing any failed request on the server logs.

**Comment by realashleybailey** [comment]
Could you attempt to rescan your libraries in the settings making sure to add them all to Wizarr and then retry the user creation

**Comment by vandie** [comment]
> Could you attempt to rescan your libraries in the settings making sure to add them all to Wizarr and then retry the user creation

Is it not supported to only allow some libraries right now?

**Comment by realashleybailey** [comment]
My thoughts are that this issue may relate to a recent bug that was reported to us where when creating a Jellyfin account with no Libraries causes the request to fail on Wizarr end, but does create the account on the Jellyfin end.

**Comment by vandie** [comment]
Selecting the playlists collection which I otherwise wouldn't include does fix the issue 😅
