### ISSUE TITLE
New users not added to Jellyseer

### ISSUE THREAD

**Issue by bennysp** [Wizarrrr/wizarr#254]
**Versions:**
Wizarr: `v3.4.1`
Jellyfin: `v10.8.10`
Jellyseerr: `v1.7.0`

**Issue:**
I have setup Jellyseerr with the Jellyseerr URL/API/ServiceType. I have setup the Jellyfin integration. I then create an invitation to all libraries. When accepting the invitation, there are no errors on screen or in the logs, but only the Jellyfin user is created. No Jellyseerr user is created.

> NOTE: On 2.x Wizarr, my Jellyseerr users were created and working with the same URL and API key

**Comment by realashleybailey** [comment]
Okay, sounds like an issue with Wizarr not being able to speak to Jellyseerr, what Ill be doing is adding same API verification tool I have for making sure you connect a Plex or Jellyfin server correctly to Jellyseerr, hopefully this will help user verify issues of connectivity. You are in good luck though aslong as your on the most recent version of Jellyseerr, users Jellyfin accounts are supposed to be automatically created when they login, so dont worry about Jellyfin users not ever being able to access Jellyseerr

**Comment by bennysp** [comment]
Good point. The user is auto created when logging into Jellyseerr. 
I think that verification will help. Right now, without adding the user up front, I get to step one and cannot click Next beyond the Jellyfin "Join and Download" step.

Look forward to the validation to see if there is a communication error somewhere on my end.

**Comment by realashleybailey** [comment]
Yes that behaviour is normal and expected, V3 does not have the same steps as V2 in the wizard, we are working on creating upgraded steps for Discord, Request, and Tutorial, these were supposed to be out early next week but have been delayed while we fixed issue relating to ARM builds of Wizarr for Docker
