### ISSUE TITLE
Feature Suggestion: Change video quality to maximum on behalf of a joined user?

### ISSUE THREAD

**Issue by SweetMNM** [Wizarrrr/wizarr#26]
One of the more annoying things about plex is having new devices and users transcode to 720p, causing all sorts of issues. Could it be possible to make a request to the plex.tv api, on behalf of the joined user (they will need to auth wizarr with their plex account), and change the video quality to maximum on their devices?

**Comment by mtthidoteu** [comment]
Ah, I do not think this is possible unfortunately, as the Video Quality Settings are a client setting and I don't think the PlexAPI supports changing Settings on the client.

**Comment by SweetMNM** [comment]
There is a plex.tv api route that can be called using an api token if one is extracted through having the user authenticate Wizarr.
It's at `https://plex.tv/api/v2/user/settings` and now that I am inspecting the network request made using the developer tools it could also be used to streamline all of the other annoyances that setting up plex entails. I believe it could also be used to unpin the default plex services such as `Discover` and `Movies & Shows` from the sidebar, it requires further investigation and testing but it's definitely possible since those type of settings are synced on a device type basis.

If you login to plex from 2 different browser instances you can see for your self that the sidebar pins and remove video quality settings are updated across them using the api route mentioned above. If you change the video quality setting on one browser, and reload plex on the other one you can see it updates.

I know it doesn't update the plex windows app for example if you change it on browser, but it *might* update **all** plex windows apps you use if you change it "from" a windows app. Same applies for all android devices you use if you update it "from" an android device, it just needs further testing to verify and see exactly what properties cause it to update the settings for what type of clients. High chance it is related to the `X-Plex-Product` param that is sent over with the request to said api route. In the case of web it gets the value of `Plex Web`.

**Comment by MiranoVerhoef** [comment]
@mtthidoteu 

First and foremost thank you so much for providing this, this streamlines my process so much.

Would you be able to maybe reopen this issue and take a look if this is possible to automate?
