### ISSUE TITLE
500 error on load of invitation url

### ISSUE THREAD

**Issue by mcmasterp** [Wizarrrr/wizarr#27]
here is the log info corresponding to the error:

```ERROR:app:Exception on /j/FGFHFF [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 7043, in get
    return clone.execute(database)[0]
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 4408, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/data/app/web.py", line 30, in welcome
    resp = make_response(render_template('welcome.html', name=Settings.get(
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 6595, in get
    return sq.get()
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 7046, in get
    raise self.model.DoesNotExist('%s instance matching query does '
app.SettingsDoesNotExist: <Model: Settings> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."key", "t1"."value" FROM "settings" AS "t1" WHERE ("t1"."key" = ?) LIMIT ? OFFSET ?
Params: ['plex_name', 1, 0]
ERROR:root:500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by mtthidoteu** [comment]
> here is the log info corresponding to the error:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/peewee.py", line 7043, in get
>     return clone.execute(database)[0]
>   File "/usr/local/lib/python3.10/site-packages/peewee.py", line 4408, in __getitem__
>     return self.row_cache[item]
> IndexError: list index out of range
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "/data/app/web.py", line 30, in welcome
>     resp = make_response(render_template('welcome.html', name=Settings.get(
>   File "/usr/local/lib/python3.10/site-packages/peewee.py", line 6595, in get
>     return sq.get()
>   File "/usr/local/lib/python3.10/site-packages/peewee.py", line 7046, in get
>     raise self.model.DoesNotExist('%s instance matching query does '
> app.SettingsDoesNotExist: <Model: Settings> instance matching query does not exist:
> SQL: SELECT "t1"."id", "t1"."key", "t1"."value" FROM "settings" AS "t1" WHERE ("t1"."key" = ?) LIMIT ? OFFSET ?
> Params: ['plex_name', 1, 0]
> ERROR:root:500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
> ```

This means that for some reason you have not set a Plex Server name (in Settings). I've set a default name in case of this happening.
