### ISSUE TITLE
[Feature Request] Support mattermost

### ISSUE THREAD

**Issue by tibers** [Wizarrrr/wizarr#278]
I'm not sure how to use typescript(?) which seems to be what this is written in. But it would be nice to add support for adding users to mattermost via their [create user API](https://api.mattermost.com/#tag/users/operation/CreateUser). There's even a [python mattermost driver](https://github.com/Vaelor/python-mattermost-driver) which looks to get us most of the way there.

**Comment by realashleybailey** [comment]
We love your enthusiasm. this is not something we would be looking to work on at this present moment, we are working on a future plugin store and I feel this would be an awesome plugin.
