### ISSUE TITLE
[BUG] unable to join V3-beta

### ISSUE THREAD

**Issue by VozDeOuro** [Wizarrrr/wizarr#281]
![image](https://github.com/Wizarrrr/wizarr/assets/36045463/81f2aa63-327a-44ed-b9a6-89b117d58d76)

When i accept the invitation, that happens and the user is not invited successful. 

Logs don't appear to show anything critical.

```
"GET /api/invitations/LYZKGC/verify HTTP/1.1" 200 35 "https://invite.lcsv.com.br/j/LYZKGC"
03:55:53 INFO 127.0.0.1 - - [2023-10-29 03:55:53] "GET /api/invitations/LYZKGC/verify HTTP/1.0" 200 277 0.004628
"POST /api/plex HTTP/1.1" 200 68 "https://invite.lcsv.com.br/j/LYZKGC"
03:56:06 INFO 127.0.0.1 - - [2023-10-29 03:56:06] "POST /api/plex HTTP/1.0" 200 310 0.859272
04:01:24 DEBUG https://plex.tv:443 "POST /api/home/users?title=sagewa2297@jybra.com HTTP/1.1" 403 None
```
I open the same on discord:
https://discord.com/channels/1020742926856372224/1168090903567663176

**Comment by gerryflux** [comment]
I still have this exact issue, running the latest version of Wizarr (docker).
