### ISSUE TITLE
[FEATURE] Separate internal and external URLs

### ISSUE THREAD

**Issue by ayykamp** [Wizarrrr/wizarr#286]
Introduce Separate internal and external URLs just like in overseerr/jellyseerr. Use the internal URL for communication and the external URL to show to an invited user. Currently if I set the jellyfin URL to `http://jellyfin:8096` the invited user is shown this url as well which isnt much use since they obviously cant access my docker network. Thank you
![image](https://github.com/Wizarrrr/wizarr/assets/32194363/d5c85281-c8d7-477d-b644-68267e132f58)

**Comment by realashleybailey** [comment]
This is already been implemented and is currently in the Beta Build preparing for release soon

**Comment by ayykamp** [comment]
Is it in 3.4.8?
