### ISSUE TITLE
Make email not required

### ISSUE THREAD

**Issue by Y0ngg4n** [Wizarrrr/wizarr#288]
Would be nice to make email not required for registration.

**Comment by realashleybailey** [comment]
> Would be nice to make email not required for registration.

This is not something we would be interested in currently, we have intentions to add future SMTP functionality, and having emails already there would avoid issues later down the line.

**Comment by hacshacdgacs** [comment]
Just checking to see if this is something that might be up for consideration again? I don't personally have the need for knowing any of my users email addresses

**Comment by Y0ngg4n** [comment]
@hacshacdgacs yeah same
