### ISSUE TITLE
Fix wrong (German) translation on homepage

### ISSUE THREAD

**Issue by iophobia** [Wizarrrr/wizarr#289]
I'm aware that Wizarr is localized by Weblate. But as a German user I stumbled over this mishap (see attachment). It seems like the variable for the server name was just turned into a hardcoded "names Server". I've found no way to address that so I thought opening a ticket would make sense.

I'm on v3.4.2 by the way.
![wizarr](https://github.com/Wizarrrr/wizarr/assets/21159729/3554b1b7-b12c-4291-baa9-2b33bcf60857)

Edit: Okay, seems it's as easy as exchanging `%{name}s Server` for `%{server_name}s Server` in the German app.po on line 1133. I'm not accustomed to PRs, so if anybody feels like it, your help would be appreciated.

**Comment by JamsRepos** [comment]
Hey! If you wish to contribute to translations, you can do so on our Weblate and it'd be great if you could proof read them all and correct where need be.
https://hosted.weblate.org/projects/wizarr-v3/wizarr/de/

**Comment by JamsRepos** [comment]
I've tested this on my local.

`Gib deinen Einladungscode für %{server_name}s Server ein!` works, i've submitted the suggestion to remove the `s` on the end, which should work.

Please note, the server name is grabbed from `/admin/settings/media` and uses the `Display Name`.
