### ISSUE TITLE
Error message when logging in.

### ISSUE THREAD

**Issue by mdziegiel** [wizarrrr/wizarr#314]
![Capture](https://github.com/Wizarrrr/wizarr/assets/90828329/bd45936d-ca4a-409a-9bd8-52ef779e3c28)
Error Message
Remote Config: Fetch client failed to connect to a network. Check Internet connection. Origianl error: Failed to fetch. (remoteconfig/fetch-client-network).

**Comment by realashleybailey** [comment]
This is a you issue, I believe you have some sort of blocking extension installed in your browser.
