### ISSUE TITLE
[Bug] | Login issues

### ISSUE THREAD

**Issue by mctscott123** [wizarrrr/wizarr#324]
### Are you using the latest release?

- [X] Yes, I am using the latest release.

### Have you checked a bug report doesn't already exist?

- [X] Yes, I have checked the existing bug reports.

### What happened?

I have used Wizarr quite a bit so I have had my login info saved for it, since the latest update that login info no longer works. Jot sure what to do about it, any suggestions would be much appreciated. Thanks!

(unRAID docker)

### Virtualisation

Docker

### What operating system are you seeing the problem on?

Other

### What browsers are you seeing the problem on?

Chrome

### Project Location

Local

### Bug Description

I have used Wizarr quite a bit so I have had my login info saved for it, since the latest update that login info no longer works. Jot sure what to do about it, any suggestions would be much appreciated. Thanks!

**Comment by realashleybailey** [comment]
Try opening your database.db file in a Sqlite Editor like this one https://sqliteonline.com

**Comment by rmilyard** [comment]
> Try opening your database.db file in a Sqlite Editor like this one https://sqliteonline.com

I am having same issue when open the db it is blank it seems.
