### ISSUE TITLE
[Bug] |  The switching to Simplified Chinese in the multilingual settings is not effective.

### ISSUE THREAD

**Issue by Alano-i** [wizarrrr/wizarr#326]
### Are you using the latest release?

- [X] Yes, I am using the latest release.

### Have you checked a bug report doesn't already exist?

- [X] Yes, I have checked the existing bug reports.

### What happened?

Switching to `Simplified Chinese` is not effective; it remains in `English` after the switch. Running the latest version of the Docker image.

I've also tried setting the environment variable `FORCE_LANGUAGE` to `zh_Hans`, but it didn't work either.

<img width="1386" alt="image" src="https://github.com/wizarrrr/wizarr/assets/68833595/4ee6dde8-843e-4ba7-8e56-2a12114baf9b">

### Virtualisation

Docker

### What operating system are you seeing the problem on?

macOS, iOS

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Project Location

Local

### Bug Description

Switching to `Simplified Chinese` is not effective; it remains in `English` after the switch. Running the latest version of the Docker image.

**Comment by realashleybailey** [comment]
Language strings will only be switched if they have been publicly translated on our Weblate instance, otherwise they default to English.

**Comment by Alano-i** [comment]
> Language strings will only be switched if they have been publicly translated on our Weblate instance, otherwise they default to English.

From what I observed in the previous issue, it supported Simplified Chinese. Does the new version no longer support Simplified Chinese?

**Comment by realashleybailey** [comment]
We previously used Auto Translated strings, these however are not always accurate so we removed them and only accept user submitted translations.

**Comment by Alano-i** [comment]
Where can I submit to help with translations?

**Comment by Alano-i** [comment]
> https://hosted.weblate.org/projects/wizarr-v3/wizarr/

<img width="862" alt="image" src="https://github.com/wizarrrr/wizarr/assets/68833595/b9e38fd3-cfda-448d-9185-ed14910f95a4">
We have completed the translation of all the strings to Simplified Chinese (mainly thanks to @anpplex), looking forward to updating them in the latest image. Thanks!
