### ISSUE TITLE
Feature Request: Allow to choose the duration of the shares

### ISSUE THREAD

**Issue by dan3805** [Wizarrrr/wizarr#33]
### it would be interesting to be able to add a share time, so automatically the user loses access to all Libraries or Libraries of our choice after example 1 year, 3 months etc.

I know it's possible to do it with a cronjob and this script [JBOPS - plex_api_share.py](https://github.com/blacktwin/JBOPS/blob/master/utility/plex_api_share.py) but it's a lot of work to do manually ! 

 We could take advantage of the database and the wonderful web interface !

**Comment by mtthidoteu** [comment]
Implemented as of 1.6.0!
