### ISSUE TITLE
[Bug] Typo after server connection setup

### ISSUE THREAD

**Issue by devanshdesai** [wizarrrr/wizarr#334]
### Are you using the latest release?

- [X] Yes, I am using the latest release.

### Have you checked a bug report doesn't already exist?

- [X] Yes, I have checked the existing bug reports.

### What happened?

After setting up the server connection, the text says:

> **Your Done**
> You have successfully completed the setup process.

It should be:

> **You're Done**
> You have successfully completed the setup process.

### Virtualisation

Docker

### What operating system are you seeing the problem on?

Linux

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Project Location

Local

### Bug Description

There is a typo in the server connection completion screen.

### Steps to Reproduce

Successfully setup a server connection until the end completion screen.

**Comment by JamsRepos** [comment]
Hi @devanshdesai.

Thanks for the report - if you'd like in the future, you could have an attempt at contributing such minor changes to the repository, however i've done this and it's set to be merged into the next beta.
