### ISSUE TITLE
[Bug] | On invite server URL copy button gives wrong URL

### ISSUE THREAD

**Issue by remy33** [wizarrrr/wizarr#335]
### Are you using the latest release?

- [X] Yes, I am using the latest release.

### Have you checked a bug report doesn't already exist?

- [X] Yes, I have checked the existing bug reports.

### What happened?

After inviting a user, on the Join & download screen server URL shown the right external URL as well as the Open Jellyfin button works just fine(2), but copy button copy the internal server IP in URL(1).

### Virtualisation

Docker

### What operating system are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Project Location

Somewhere else (please specify in the description!)

### Bug Description

![msedge_UIbmqu8XOH](https://github.com/wizarrrr/wizarr/assets/16070787/bacaa5d3-763d-4d89-b4ee-7b420cdead86)

### Steps to Reproduce

Create new invite
Redeem the invite
Create a user
See that server URL is right ( https://wizarr.exmple.com/ )
Click on "copy" botton and paste it.
Internal Jellyfin server IP has been copied (https://192.168.x.x:8096/)

**Comment by JamsRepos** [comment]
Hi @remy33!

Thanks for the report - I've gone ahead and fixed this and will be pushing this into the [develop ](https://github.com/wizarrrr/wizarr/tree/develop) branch ready for when the next beta goes live.
