### ISSUE TITLE
[Bug] | Password and Library permissions not saved to Emby Server 4.9.0.10 (beta)

### ISSUE THREAD

**Issue by sovajri7** [wizarrrr/wizarr#336]
### Are you using the latest release?

- [X] Yes, I am using the latest release.

### Have you checked a bug report doesn't already exist?

- [X] Yes, I have checked the existing bug reports.

### What happened?

When inviting someone to my Emby server, it creates the user but password is not saved on it so user can't connect to server automatically. ALSO don't give the library permissions to user while check on Wizarr paramaters.

### Virtualisation

Docker

### What operating system are you seeing the problem on?

Linux

### What browsers are you seeing the problem on?

Firefox

### Project Location

Remote

### Bug Description

Password not saved to user on Emby Server ALSO don't give the library permissions to user while check on Wizarr paramaters.

### Steps to Reproduce

fresh install, use the Emby beta version and invite a user

**Comment by equals215** [comment]
On 4.9.x.x versions, Emby have it's user creation workflow set as :
1. Create User
2. Set users password

As the Wizarr backend doesn't differentiate between Emby and Jellyfin, a new media server type should be created for Emby and this workflow discrepancy should be reflected.

**Comment by equals215** [comment]
I'm forking to add the password set operation based on an API response differentiating factor
Based on their respective public API reference, both Jellyfin and Emby APIs have a `/System/Info/Public` endpoint, Jellyfin responds with a body that includes a key named `ProductName` and Emby doesn't include this key, making it the differentiating factor that will be used to base the workflow on. PR will come.

**Comment by Wazany** [comment]
Hello I have exactly the same problem with version 4.8.3.0.
