### ISSUE TITLE
Feature request add email to jellyfin news letter 

### ISSUE THREAD

**Issue by binarygeek119** [wizarrrr/wizarr#358]
i would like to be able to auto add the new users to the Newsletter plug in.

https://github.com/Cloud9Developer/Jellyfin-Newsletter-Plugin

**Comment by JamsRepos** [comment]
Hi @binarygeek119!

Thanks for the suggestion - unfortunately this is out of scope for our plans for this project. Whilst we'd like to have every single outcome, this wouldn't be practical long term. If we start direct plugin integrations now, there will be an endless line to come.

We do have the API which you can easily use to accomplish what you'd like, unfortunately it won't be a native solution though. Us providing API endpoints is specifically for these kind of features, so if you or someone else makes this integration link between Wizarr and this plugin, then it would work just fine without us internally having to maintain all these individual plugin integrations.
