### ISSUE TITLE
The /Join link results in a 500 error

### ISSUE THREAD

**Issue by ZGremlin** [Wizarrrr/wizarr#38]
Running this with the latest docker available.

When a user clicks "I have a Plex Account" the server returns a 500 error.  I've tried with multiple invite links, they all get a 500 error.  Everything else seems to work fine.

ERROR:app:Exception on /join [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 7043, in get
    return clone.execute(database)[0]
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 4408, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/data/app/web.py", line 89, in join
    return render_template("join.html", name=Settings.get(Settings.key == "plex_name").value, code=code)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 6595, in get
    return sq.get()
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 7046, in get
    raise self.model.DoesNotExist('%s instance matching query does '
app.SettingsDoesNotExist: <Model: Settings> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."key", "t1"."value" FROM "settings" AS "t1" WHERE ("t1"."key" = ?) LIMIT ? OFFSET ?
Params: ['plex_name', 1, 0]
ERROR:root:500 Internal

**Comment by mtthidoteu** [comment]
Sorry for the late reply. This seems to be an issue with your database. I’d recommend deleting the database and starting it up again.

**Comment by GadgetGeekNI** [comment]
I actually had the same issue. 
I set Wizarr for the first time today, very impressed. Love the concept! 
After a reboot I had to re-enter my Plex claim token and plex URL / Ombi to get it to work again otherwise I got a 500 error. 
Are we able to add Plex token, Plex URL and Ombi URL as compose env variables that I can input automatically to force it to persist across container restarts?

**Comment by mtthidoteu** [comment]
> I actually had the same issue.
> I set Wizarr for the first time today, very impressed. Love the concept!
> After a reboot I had to re-enter my Plex claim token and plex URL / Ombi to get it to work again otherwise I got a 500 error.
> Are we able to add Plex token, Plex URL and Ombi URL as compose env variables that I can input automatically to force it to persist across container restarts?

I think what is going on here is that you are not persisting the database, and therefore it is getting reset after container resets. You need to persit the /data/database volume. The Tokens are stored in the database
