### ISSUE TITLE
Wizarr doesn't ignore SSL error

### ISSUE THREAD

**Issue by Sorcier** [Wizarrrr/wizarr#39]
If you set your Plex Media Server in Secure Connection Mandatory, when you go on the web interface you're in HTTPS with SSL error (normal).
If it's the case Wizarr doesn't not ignore the SSL error and block and you have Verify URL or Token when you want to scan library.
For me the only one solution is to use NGINX Proxy Manager as "workaround" but the best would be to ignore SSL Error.

**Comment by mtthidoteu** [comment]
Unless I am mistaken, you can still just put the 'http://plex' url, non-https and it should still work. The 'Secure Connection Mandatory' is between Clients and Server, not necessarily http/https.
Try changing the URL to 'http://<plex-container>:32400'.
