### ISSUE TITLE
Invitation acceptance documentation

### ISSUE THREAD

**Issue by suckerfish** [Wizarrrr/wizarr#4]
I'm very excited that you have taken on the task of smoothing out inviting people to your Plex server. So far I think this is a great start.  As someone with over 50+ friends/family/co-workers I have definitely seen my fair share of ups and down with getting people access to my server. 

I'd say the number one thing that trips 'normal non-techie people' up with this process is going from the invitation email that Plex sends to them over to a working Plex session with the new server attached. Why? Because if you click the invitation link, it will ask you to sign into Plex. If you are already signed in on that device, then it's pretty easy. The link will simply directly connect you with the plex server. However, if you are not currently signed into Plex on that device, it will prompt you to sign in but it will _not_ connect the server to your Plex account after you sign in. You have to go back to the email and click the link again to complete the process. People seem to get tripped up by that all the time. 

I am not sure exactly the best text or wording that should be added to this process, but I do believe it should be added someplace. Or maybe the best thing would be to ask them to log into their Plex account on their current device before they click on the invite link in their email? This would also smooth things along for Overseerr access as well I do believe. Maybe something like "Hey do you have a Plex account? No? Ok please go create one here" "Oh you already have one? Please validate your Plex account is working okay by logging into Plex (button). Then come back here to continue" 

Thoughts?

**Comment by mtthidoteu** [comment]
Thanks for the feedback! It really means a lot! 

I definitely see what you mean! You know I might just try and do a "Sign in with Plex"! That could make EVERYTHING easier. 

For the admins they would have everything automatically imported and it would make sure the users have signed in on the current device!

**Comment by mtthidoteu** [comment]
Have a look at what I've done now! It isn't strictly speaking what you suggested, but I feel it is actually clearer to follow! Let me know what you think!

**Comment by suckerfish** [comment]
Hey there - I'm trying to test it out but the new UI for server settings is telling me my Plex URL or Token are wrong. I just confirmed my token is good. Maybe my URL isn't in the right format or something? In my case it's at http://192.168.1.100:32400 but it doesn't like that. (It used to back when it was a part of the docker-compose.yml). Nor does it like http://192.168.1.100, nor does it like http://192.168.1.100:32400/web - I can curl those targets from the VM this is running on no problem so the server is definitely accessible. Nothing in 'docker logs wizarr' that is telling, at all.

**Comment by suckerfish** [comment]
Hey I solved my issue above. 

Regarding this new functionality, it looks good! Takes them directly into their Plex account (forcing them to log in) and has them directly accept the invitation. I like it. 

I do have two suggestions though: 

On the screen where it says "Click the button below to be taken to Plex, here you will see an invitation from us." - I recommend adding a line to reiterate what they have to do. "Click the Checkbox icon to accept the invitation".

And on the next screen where it prompts you to download the client, I'd recommend a few sentences or so that explain that you don't need to do this at all if you plan on watching this on your computer/browser, and point them to https://plex.tv then click "Open Plex" to start watching. Because when I click the Download client button on my Mac it tries to get me to download Plex Media Server which would definitely just cause a lot of confusion. 

Great progress. Thank you!

**Comment by suckerfish** [comment]
A little bit more feedback. Regarding this page: 
![image](https://user-images.githubusercontent.com/33015972/193682000-690946ca-6661-4a90-8abf-d7fbafc34abf.png)

The text says "Click the button below to be taken to Plex, here you will see an invitation from us." 

But there are two buttons there, "Accept" and "Next"  - I could absolutely see confusion about which one to press at that moment. 

I'd recommend the wording change to "Click the 'Accept invite' button below..." and the button itself be renamed to "Accept Invite" just to make it ultra clear. Maybe move the "Next" button further to the right so they aren't right next to each other.

Also, once they do this, they are gone. Navigated away from this page. Not sure how many folks would end up making  their way back here to click 'Next' to move onto the next screen(s). Maybe add that line about "Come back to this page once you're done" like you have on a previous page.
