### ISSUE TITLE
[Bug] | Stable version still shows BETA software banner in about under advanced settings

### ISSUE THREAD

**Issue by ibphantom** [wizarrrr/wizarr#408]
### Are you using the latest release?

- [X] Yes, I am using the latest release.

### Have you checked a bug report doesn't already exist?

- [X] Yes, I have checked the existing bug reports.

### What happened?

Stable version still shows BETA software banner in about under advanced settings

### Virtualisation

Unraid

### What operating system are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Firefox, Chrome

### Project Location

Local

### Bug Description

Stable version still shows BETA software banner in about under advanced settings

### Steps to Reproduce

Go to settings, go to the bottom at advanced settings and click about
The Stable version still shows BETA software banner.

**Comment by MrDynamo** [comment]
Fixed in [819223e](https://github.com/wizarrrr/wizarr/pull/407/commits/819223e0b7dd419926946667c5e83837ef586052)](https://github.com/wizarrrr/wizarr/pull/407/commits/819223e0b7dd419926946667c5e83837ef586052)
