### ISSUE TITLE
[Bug] | Plex Home users don't work

### ISSUE THREAD

**Issue by Jphannon1** [wizarrrr/wizarr#411]
### Are you using the latest release?

- [X] Yes, I am using the latest release.

### Have you checked a bug report doesn't already exist?

- [X] Yes, I have checked the existing bug reports.

### What happened?

When adding a plex home user using the invite option, it doesn't work and gives the error:

"We were unable to accept the plex inite on your behalf, please accept the invite manually through plex or your email". But there is no invite on the plex account or email.

On the plex owners account a new user has been added to home as a managed account with just an email address and not the invited users plex account.

![Screenshot 2024-05-05 120401](https://github.com/wizarrrr/wizarr/assets/112480958/29d0a0b1-42c3-45a2-99e9-abc910e30110)

### Virtualisation

Docker

### What operating system are you seeing the problem on?

Linux

### What browsers are you seeing the problem on?

Chrome

### Project Location

Local

### Bug Description

When trying to add a plex home user, it does not work and simply adds the plex accounts email to the home as a managed account.

### Steps to Reproduce

When creating a invite for plex, select "Allow Plex Home Access" and try to sign up with a plex account

**Comment by JamsRepos** [comment]
This feature does not work and cannot work. I was investigating this yesterday and the API endpoints just don’t exist for it unfortunately. 

So, this feature is being removed within #407 and cannot be fixed unfortunately. 

Plex does now allow the invitation of existing Plex users through their API, only the creation of Managed Users.

**Comment by Jphannon1** [comment]
Ok, not too difficult to add them to plex home manually once they have been invited, thanks for letting me know
