### ISSUE TITLE
Support Timezones

### ISSUE THREAD

**Issue by didyouexpectthat** [Wizarrrr/wizarr#42]
The default time zone supported by Wizarr is GMT. Usually, we can change this via Docker environment variables but this functionality is not supported on Wizarr (yet). Right now, it's 2023/01/18 5:53 PM Pacific time but the times show created 2023/01/19 01:53. 

Feature request to support telling docker-compose file with environment variables to set the time zone of the container. 
`- TZ=America/Los_Angeles`

![image](https://user-images.githubusercontent.com/1329077/213337402-065cf568-7d2b-4285-b1b7-5bbfd331b788.png)
![image](https://user-images.githubusercontent.com/1329077/213337497-3a7af08f-99b2-48cd-8992-4bd307563556.png)

**Comment by didyouexpectthat** [comment]
Or, it is possible that  TZ= works, but the value stored in the expiry doesn't respond to timezone changes. For example:
![image](https://user-images.githubusercontent.com/1329077/213337872-e132cda6-1644-4e37-b6c2-2b7e63022948.png)

The used is before the created date now. I would expect that changing the timezone in the system would update the timestamps across the platform.

**Comment by mtthidoteu** [comment]
Added Support for TZ in V1.0.1
https://github.com/Wizarrrr/wizarr/releases/tag/1.0.1
