### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by comradekingu** [Wizarrrr/wizarr#43]
Expected to find in the form of "COPYING" or "LICENSE".
Says Apache 2.0 in https://hosted.weblate.org/projects/wizarr/app/#information

**Comment by mtthidoteu** [comment]
Not sure what you mean. I've changed the translations to MIT by the way

**Comment by comradekingu** [comment]
That is just worse on account of there being no patent protection.
My problem is the main repo (here on GitHub) doesn't have a license stated, or so it seems.

**Comment by mtthidoteu** [comment]
The GitHub repo uses the « Common Clause » license now: https://commonsclause.com/On 23 Jan 2023, at 13:54, Allan Nordhøy ***@***.***> wrote:﻿
That is just worse on account of there being no patent protection.
My problem is the main repo (here on GitHub) doesn't have a license stated, or so it seems.

**Comment by comradekingu** [comment]
@mtthidoteu That doesn't meet the gratis hosting requirements of Hosted Weblate, since it isn't a libre license.
Also, I don't think going Apache 2.0 → MIT is possible because of the patent protection.

I would go AGPLv3+ on everything, and ask the current contributors if that is OK.
It has to be done anyway, because all contributions taken before there was any licensing in place is effectively copyright only. This means the project can't legally be distributed with those changes.

Good idea to do it now and get it all sorted with just the 7 other external contributors.
I am fine with AGPLv3+.

**Comment by mtthidoteu** [comment]
> @mtthidoteu That doesn't meet the gratis hosting requirements of Hosted Weblate, since it isn't a libre license. Also, I don't think going Apache 2.0 → MIT is possible because of the patent protection.
> 
> I would go AGPLv3+ on everything, and ask the current contributors if that is OK. It has to be done anyway, because all contributions taken before there was any licensing in place is effectively copyright only. This means the project can't legally be distributed with those changes.
> 
> Good idea to do it now and get it all sorted with just the 7 other external contributors. I am fine with AGPLv3+.

Okay, I'll admit this is my first time distributing a program properly so I had not thought about the implications properly. I think for the sake of convention, convenience and transparency I will be moving the entire project to an MIT license.
