### ISSUE TITLE
[Bug/Solution] | Setting a Github Rate limit for statistics on the site

### ISSUE THREAD

**Issue by ramazansancar** [wizarrrr/wizarr#440]
### Are you using the latest release?

- [X] Yes, I am using the latest release.

### Have you checked a bug report doesn't already exist?

- [X] Yes, I have checked the existing bug reports.

### What happened?

It may be better to create a script for the statistics section of your website and run it periodically with cron via github action, keeping the data in a json file in the repo or in the docs to feed the website.

![image](https://github.com/wizarrrr/wizarr/assets/8878055/1020c8ad-162b-45fb-8682-6951349685b7)

### Virtualisation

Other

### What operating system are you seeing the problem on?

Other

### What browsers are you seeing the problem on?

Chrome

### Project Location

Somewhere else (please specify in the description!)

### Bug Description

It may be better to create a script for the statistics section of your website and run it periodically with cron via github action, keeping the data in a json file in the repo or in the docs to feed the website.

See here: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting

**Comment by albinmedoc** [comment]
I agree, this should really be fixed. 

It looks like the script is fetching 100 commits/request and summing it up to give the total number of commits. 
When I'm writing this, it makes 24 request just to get the number of commits. Number of request will just increase when wizarr grows. 

The same if for contributors. 100 contributors/request. 

Currently, 29 request are made to github when I visit [wizarr.dev](http://wizarr.dev)

**Comment by JamsRepos** [comment]
I don't actually have access to where this site is hosted, it'll need to be moved eventually. For now, i've removed the statistics off here, I would make the repository open but I believe TailwindUI was used and paid for in this repo so it's probably best I don't.

**Comment by ramazansancar** [comment]
Thanks for your review @JamsRepos
