### ISSUE TITLE
[Bug] | Blank white webpage on iOS and Internet Browser on Android 

### ISSUE THREAD

**Issue by DrDMoney** [wizarrrr/wizarr#448]
### Are you using the latest release?

- [X] Yes, I am using the latest release.

### Have you checked a bug report doesn't already exist?

- [X] Yes, I have checked the existing bug reports.

### What happened?

Just used wizarr to have my plex users make their own jellyfin accounts. Nearly all iOS users reported back the the site loads a completely white webpage with nothing to do or interact with. I saw the exact same issue accrue using the basic internet browser app on android. I am not able to figure out why this is happening. 
 

### Virtualisation

Docker

### What operating system are you seeing the problem on?

iOS

### What browsers are you seeing the problem on?

Chrome, Safari

### Project Location

Remote

### Bug Description

Unable to load website with iOS browsers. Tested safari and chrome. 
Android internet browser also has same issue.

**Comment by ptscreens** [comment]
I have the same issue - All browsers ONLY outside of the local network have the same issue. Tested on iOS, Android and MacOS with Chrome, Safari (iOS & MacOS Only), Firefox, Samsung Browser (Android Only). 

Wizarr in docker, NGINX Proxy Manager in front (both locally and externally).

Works fine over different VLANs, just not externally, so not a routing issue. 

More than happy to test etc.. if needed.

**Comment by DrDMoney** [comment]
I have had a lot of inconsistencies trying to fix this issue where I also started having issues in multiple browsers but it wasn't always present.  I disabled my dns proxy on cloudflare and that seems to have done the trick. I'm not sure what in the code is causing the issue where I can't use a DNS proxy service.

**Comment by DrDMoney** [comment]
> You can use cloudflare, you must disable the auto minify and the rocket settings I believe. Due to the nature of Vue, it renders the page after the DOM is loaded, not before. So it’s breaking the JS.
> 
> 
 I turned off the minify and turned DNS proxy back on but still having similar issues.

**Comment by JamsRepos** [comment]
I believe the setting in question is “Rocket Loader” which can be found under Speed > Optimization

**Comment by DrDMoney** [comment]
> I believe the setting in question is “Rocket Loader” which can be found under Speed > Optimization

I figured it out. I forgot to purge the DNS cache in cloudflare. So it was still pulling the broken minify code.
