### ISSUE TITLE
[Feature] Password policy

### ISSUE THREAD

**Issue by Y0ngg4n** [wizarrrr/wizarr#454]
There was a password policy via env variables. It would be better to have it in the admin ui.

**Comment by albinmedoc** [comment]
I know this doesn't answer your question. 

But here is the environment variables for people that doesn't know they exist. 

| ENV                    | Default |
|------------------------|---------|
| MIN_PASSWORD_LENGTH    | 8       |
| MIN_PASSWORD_UPPERCASE | 1       |
| MIN_PASSWORD_NUMBERS   | 1       |
| MIN_PASSWORD_SPECIAL   | 0       |

**Comment by Y0ngg4n** [comment]
@albinmedoc as far as i know this envs do nothing currently

**Comment by albinmedoc** [comment]
In the code they are used. 

But it'/ for the Wizarr password. 

Requirements for the plex password can't we come up with.

**Comment by Y0ngg4n** [comment]
@albinmedoc the meaning of those envs whas for jellyfin/... passwords

**Comment by albinmedoc** [comment]
They are currently in use for the Wizarr accounts. 

https://github.com/wizarrrr/wizarr/blob/master/apps/wizarr-backend/wizarr_backend/app/models/wizarr/accounts.py

**Comment by Y0ngg4n** [comment]
ah ok. yeah but it does not make sense to use them. would be better to include it in the ui.

**Comment by JamsRepos** [comment]
> ah ok. yeah but it does not make sense to use them. would be better to include it in the ui.

Not for the niche amount of use cases it would have. If you want to change it, you can. It makes perfect sense to leave them as environment variables, you have the function to do what you require, there's not much need for it in the UI at present.

**Comment by Y0ngg4n** [comment]
@JamsRepos is the password policy now also applied to jellyfin passwords?
