### ISSUE TITLE
Feature Request: reverse proxy configuration documentation

### ISSUE THREAD

**Issue by LeeDurant** [Wizarrrr/wizarr#49]
I use SWAG for my reverse proxy, which is driven by nginx. Documentation on how to support reverse proxy would be helpful for new users.

**Comment by LeeDurant** [comment]
I used the following for nginx, based on what was already in the system for sonarr. It worked just fine, so long as I replaced all the necessary pieces.

## Version 2023/02/12
# make sure that your wizarr container is named wizarr
# make sure that your dns has a cname set for "join.YOURDOMAIN.com"

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name join.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth (requires ldap-location.conf in the location block)
    #include /config/nginx/ldap-server.conf;

    # enable for Authelia (requires authelia-location.conf in the location block)
    #include /config/nginx/authelia-server.conf;

    # enable for Authentik (requires authentik-location.conf in the location block)
    #include /config/nginx/authentik-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable for ldap auth (requires ldap-server.conf in the server block)
        #include /config/nginx/ldap-location.conf;

        # enable for Authelia (requires authelia-server.conf in the server block)
        #include /config/nginx/authelia-location.conf;

        # enable for Authentik (requires authentik-server.conf in the server block)
        #include /config/nginx/authentik-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app wizarr;
        set $upstream_port 5690;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }

    location ~ (/sonarr)?/api {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app wizarr;
        set $upstream_port 5690;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

   }
}

**Comment by mtthidoteu** [comment]
> I used the following for nginx, based on what was already in the system for sonarr. It worked just fine, so long as I replaced all the necessary pieces.
> 
> ```
> 
> ## Version 2023/02/12
> # make sure that your wizarr container is named wizarr
> # make sure that your dns has a cname set for "join.YOURDOMAIN.com"
> 
> server {
>     listen 443 ssl;
>     listen [::]:443 ssl;
> 
>     server_name join.*;
> 
>     include /config/nginx/ssl.conf;
> 
>     client_max_body_size 0;
> 
>     # enable for ldap auth (requires ldap-location.conf in the location block)
>     #include /config/nginx/ldap-server.conf;
> 
>     # enable for Authelia (requires authelia-location.conf in the location block)
>     #include /config/nginx/authelia-server.conf;
> 
>     # enable for Authentik (requires authentik-location.conf in the location block)
>     #include /config/nginx/authentik-server.conf;
> 
>     location / {
>         # enable the next two lines for http auth
>         #auth_basic "Restricted";
>         #auth_basic_user_file /config/nginx/.htpasswd;
> 
>         # enable for ldap auth (requires ldap-server.conf in the server block)
>         #include /config/nginx/ldap-location.conf;
> 
>         # enable for Authelia (requires authelia-server.conf in the server block)
>         #include /config/nginx/authelia-location.conf;
> 
>         # enable for Authentik (requires authentik-server.conf in the server block)
>         #include /config/nginx/authentik-location.conf;
> 
>         include /config/nginx/proxy.conf;
>         include /config/nginx/resolver.conf;
>         set $upstream_app wizarr;
>         set $upstream_port 5690;
>         set $upstream_proto http;
>         proxy_pass $upstream_proto://$upstream_app:$upstream_port;
> 
>     }
> 
>     location ~ (/sonarr)?/api {
>         include /config/nginx/proxy.conf;
>         include /config/nginx/resolver.conf;
>         set $upstream_app wizarr;
>         set $upstream_port 5690;
>         set $upstream_proto http;
>         proxy_pass $upstream_proto://$upstream_app:$upstream_port;
> 
>    }
> }
> ```

I've just created one! 
See https://docs.wizarr.dev/getting-started/reverse-proxy

I am not familiar with Authelia so I'd rather not mess things up, you're welcome to add a SSO section to the documentation by doing a PR !
