### ISSUE TITLE
Request : Organizr integration

### ISSUE THREAD

**Issue by ItsM3rry** [Wizarrrr/wizarr#5]
Hello,

could you add an Organizr integration for this please

**Comment by mtthidoteu** [comment]
I don't personally use Organiser but I would love to hear more about this! what sort of integration did you have in mind?

**Comment by suckerfish** [comment]
I use it but I'm not sure what @ItsM3rry would be referring to so I'm also curious to know.

**Comment by mtthidoteu** [comment]
Closing this for now
