### ISSUE TITLE
Feature Request: Better instructions for creating new Plex Account

### ISSUE THREAD

**Issue by guiltyvictim** [Wizarrrr/wizarr#55]
Tested this out with my friend, who said it's quite easy to miss the message 'To join our Plex server, create a Plex account! Once you're done, come back here!' which would be more relevant if user is using a mobile and doesn't know to navigate back to the old tab.

So perhaps instead of having the message when there's a choice to Create Plex Account / I have a Plex Account - make it so that when clicking Create Plex Account, to go through a quick 'step by step' graphics (like in online surveys that indicates progress), emphasising that they need to come back to this page / tab to finish the process.

And when they click the link to Create a Plex Account, the page itself should update to show the join page fields with the instructions still visible above - so that user recognises they were on this page before.

Just thinking the users most needing to go through Wizarr to set themselves up are probably not very tech savvy in the first place, so we need to be extra accommodating and idiot proof things.

**Comment by mtthidoteu** [comment]
As a matter of fact, I have just finished developing such a feature. We will be using Plex SSO directly. Essentially, the users will be taken to Plex, and then redirected to Wizarr. The invitation will be automatically sent AND accepted using the API!
It'll be much better!

It is currently on the Dev branch if you want to try it out!
