### ISSUE TITLE
Feature Request: Translate into different languages, Nginx Configuration

### ISSUE THREAD

**Issue by ItsM3rry** [Wizarrrr/wizarr#6]
Hello and thanks for your nice -arr container, 
it's very useful for big Plex servers :)

I have a feature request, could you add some translations and add a .conf file for nginx or swag reverse proxy ?

Thanks

**Comment by EinsteiniumFr** [comment]
@mtthidoteu For French, I am available

**Comment by sebstrgg** [comment]
@mtthidoteu I'd love multilingual support as well. I can assist with Swedish :)

**Comment by Glynax** [comment]
+1 for SWAG/nginx config
https://github.com/linuxserver/reverse-proxy-confs I believe you have to add it here so it goes to everyone.

**Comment by totof-l** [comment]
Hi, another +1 for SWAG config !
And if the config file could have exemples for whitelisting the paths "/join", "/j/*" and "/setup*", it could be great :)

**Comment by neoestremi** [comment]
Thank you for the french support, there was some mistakes, I checked every string and rectified what needed to be (mostly the name of Plex menu/options and ponctuation).
Do I need to make a PR to merge the modifications ?

**Comment by mtthidoteu** [comment]
No normally if you did it on the Weblate it should be pushed straight away ! Or if you put it in the file directly a PR could be good ! Cheers On 23 Jan 2023, at 06:02, NeoToxic ***@***.***> wrote:﻿
Thank you for the french support, there was some mistakes, I checked every string and rectified what needed to be (mostly the name of Plex menu/options and ponctuation).
Do I need to make a PR to merge the modifications ?

**Comment by neoestremi** [comment]
> 

It was on Weblate :)
Cheers

**Comment by mtthidoteu** [comment]
> It was on Weblate :)
> Cheers

Perfect! It has been automatically pushed then! You can try it out with the Wizarr:dev image to try it out as it follows the GitHub repo
