### ISSUE TITLE
Feature Request: Allow editing of user workflow copy

### ISSUE THREAD

**Issue by LeeDurant** [Wizarrrr/wizarr#60]
It would be helpful if there was an in-system editor for the copy used to help users register and log in. I intend to use this as a way to add custom translation for friends who speak other languages.

**Comment by mtthidoteu** [comment]
The app is being translated into multiple languages! You can help us out if you want !On 17 Feb 2023, at 15:29, LeeDurant ***@***.***> wrote:﻿
It would be helpful if there was an in-system editor for the copy used to help users register and log in. I intend to use this as a way to add custom translation for friends who speak other languages.

**Comment by PilaScat** [comment]
But if I want different texts? Not only translated?
You could add in /config a file with every string to customize them
