### ISSUE TITLE
any chances or plans for supporting emby and jellyfin ?

### ISSUE THREAD

**Issue by aniel300** [Wizarrrr/wizarr#64]
is it possible and/or do u have any plans for supporting emby and jellyfin ?

**Comment by zmweske** [comment]
Check out this issue: 
https://github.com/Wizarrrr/wizarr/issues/2

And this other project:
https://github.com/hrfee/jfa-go

**Comment by aniel300** [comment]
yes we talked about this in the discord, u did said u are planning on supporting them right?

**Comment by mtthidoteu** [comment]
> yes we talked about this in the discord, u did said u are planning on supporting them right?

:)
