### ISSUE TITLE
Use Local Plex Server in configuration

### ISSUE THREAD

**Issue by PilaScat** [Wizarrrr/wizarr#67]
I have not a Plex URL to fullfill this, why I can't add my plex local ip:port like in overseer?
![image](https://user-images.githubusercontent.com/12989749/220104204-a16dd01c-a835-4b96-9513-1e4e4afa4885.png)

**Comment by mtthidoteu** [comment]
This should be possible, what do the logs say? Can the wizarr container access that host?

**Comment by PilaScat** [comment]
`WARNING:urllib3.connection:Certificate did not match expected hostname: 192.168.1.20. Certificate: {'subject': ((('commonName', '*.f5a4f1a65dsfd1a6.plex.direct'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', "Let's Encrypt"),), (('commonName', 'R3'),)), 'version': 3, 'serialNumber': '115855aa1s1ds5d5s51', 'notBefore': 'Jan 23 18:26:57 2023 GMT', 'notAfter': 'Apr 23 18:26:56 2023 GMT', 'subjectAltName': (('DNS', '*.f5a4f1a65dsfd1a6.plex.direct'),), 'OCSP': ('http://r3.o.lencr.org',), 'caIssuers': ('http://r3.i.lencr.org/',)}`

**Comment by 8321876218** [comment]
Is your Plex server set to Require secure connections, or only Prefer them? You may try to replace http://192.168.1.20:32400 with https://192-168-1-20..f5a4f1a65dsfd1a6.plex.direct:32400 (I think). I believe HTTP will only work when Requiring secure connections if Wizarr is on the same machine, where you would type http://localhost:32400

**Comment by PilaScat** [comment]
Is set on Prefer, but even with ip.hash.plex.direct it doesn't work

**Comment by 8321876218** [comment]
Just to be specific, the format you entered was https://ip.hash.plex.direct:port correct?

**Comment by PilaScat** [comment]
yes, copied the url from overseerr

**Comment by 8321876218** [comment]
I would like to point out that Overseerr does not include the port at the very end of the https link, so it would need to be copied from Overseerr and then appended with :32400

**Comment by PilaScat** [comment]
in fact i forget it ahahha
now it works

**Comment by 8321876218** [comment]
The tiny details will get you some times! Glad you got it
