### ISSUE TITLE
Can't connect to Plex server

### ISSUE THREAD

**Issue by AD1995** [Wizarrrr/wizarr#7]
When trying to configure Wizarr to connect to my Plex server, I get the following error.

`ERROR:root:HTTPSConnectionPool(host='plex.domain.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))
`

**Comment by AD1995** [comment]
I've got the APP_URL environment variable set to join.mydomain.com
I've just copied the docker compose example from the readme

**Comment by mtthidoteu** [comment]
Sorry to ask this, but you are replacing mydomain with your domain, right?

It looks as if your Plex URL doesn't have a valid SSL certificate. Do you use other URLs to access it ?

**Comment by AD1995** [comment]
Yeah. Just changed it for reporting this issue so my domain isn't just out
there 😊

I'm using the Linux server SWAG container for my SSL certs

**Comment by mtthidoteu** [comment]
This seems to be an error with your Plex Container's HTTPs. I would check out [linuxserver's discord](https://discord.gg/XcJYKWUh) to see if they can help you fix it!
