### ISSUE TITLE
Feature Request: Custom Videos for Config

### ISSUE THREAD

**Issue by DraneLixX** [Wizarrrr/wizarr#71]
It would be nice if it would be possible to specify a Custom YT-Link or even better Directly stream it from the server.
As a little Extra, i would ask for a Language button for the User and Maybe Language Specific Videos that would be Awesome.

Otherwise, Nice work, I appreciate you for sharing it with us.

**Comment by 8321876218** [comment]
You can use the integrated HTML as a template and change the YT links to suit your requirements. then supply it as the custom HTML in the Settings page. I'll leave the second part for the actual dev to comment on.

**Comment by mtthidoteu** [comment]
Indeed, this is possible via the Custom HTML !

**Comment by DraneLixX** [comment]
Hi, 

I'm sorry, but I'm not smart enough to do this properly.
If I just take the tips.html and paste it into the custom HTML, then I get some strange alignment 

Could you be so kind to provide me with the right snippet where I change the links?

<img width="372" alt="image" src="https://user-images.githubusercontent.com/33241086/221188135-aa9339fe-e55e-414e-a880-068c20983ee2.png">

**Comment by mtthidoteu** [comment]
> Hi,
> 
> I'm sorry, but I'm not smart enough to do this properly. If I just take the tips.html and paste it into the custom HTML, then I get some strange alignment
> 
> Could you be so kind to provide me with the right snippet where I change the links?
> 
> <img alt="image" width="372" src="https://user-images.githubusercontent.com/33241086/221188135-aa9339fe-e55e-414e-a880-068c20983ee2.png">

I see.

At this stage for your use case and what you are trying to achieve I would recommend going to YouTube, clicking « Embed » on the video you want and playing around with that instead of trying to copy that template. It uses JavaScript and it’s all over the place with styling, although i suppose you could try going a few divs down.
