### ISSUE TITLE
[HELP] ERROR - Failed to get token from Plex

### ISSUE THREAD

**Issue by ebb-earl-co** [Wizarrrr/wizarr#75]
**Describe the bug**
Wizarr is able to generate invite links, and is able to see the libraries of my Plex instance, but when trying to follow the link and set up an account for a new user, the Plex sign-up page hangs, spinning in a circle and not resolving. The logs say 
```wizarr  | 2023-02-24 10:22:25,165 - ERROR - Failed to get token from Plex```.

I am using the Docker compose setup and SWAG as the reverse proxy, using the exact configuration files [from the documentation](https://docs.wizarr.dev/getting-started/reverse-proxy). The `APP_URL` environment variable is set as https://wizarr.mydomain.tld.

**Screenshots**
![image](https://user-images.githubusercontent.com/11299014/221249867-0d7a4b5c-8138-4c6e-9686-a2d47675f62c.png)
![image](https://user-images.githubusercontent.com/11299014/221250930-4a8a0a8a-e97b-40ae-8f68-45f87bea94ed.png)

**Logs**
If applicable, add logs to help explain your problem
```shell
wizarr  | [2023-02-24 10:17:21 -0700] [1] [INFO] Starting gunicorn 20.1.0
wizarr  | [2023-02-24 10:17:21 -0700] [1] [INFO] Listening at: http://0.0.0.0:5690 (1)
wizarr  | [2023-02-24 10:17:21 -0700] [1] [INFO] Using worker: sync
wizarr  | [2023-02-24 10:17:21 -0700] [7] [INFO] Booting worker with pid: 7
wizarr  | [2023-02-24 10:17:21 -0700] [8] [INFO] Booting worker with pid: 8
wizarr  | [2023-02-24 10:17:21 -0700] [10] [INFO] Booting worker with pid: 10
wizarr  | 2023-02-24 10:22:25,165 - ERROR - Failed to get token from Plex
```

**Additional context**
Wizarr is running as a Docker container on an x86_64 Debian 11 host, version 1.6.5 _on the same host as the Plex instance_ (also Docker container). I am able to resolve https://wizarr.mydomain.tld externally, and create new invitations, change Wizarr server settings, etc.

As you can see from the screenshot, I tried changing the `Plex URL` in the Settings at https://wizarr.mydomain.tld/settings/# from `APP_URL` environment variable value to http://plex:32400 as referenced in issue #20, but the same error occurs. Some of the advice from that issue was to try to drop to a Python session and use the `plexapi` library directly for troubleshooting: I have done so and I **am** able to query my library, etc. with the same Plex token that is passed to the Wizarr settings.

Do I have to have a Plex pass for this to work? I should have started with that question!

**Comment by mtthidoteu** [comment]
that's strange, do the logs not give you any more info?
The new update will rewrite the whole way it does the oauth anyway, this is strange though!

**Comment by ebb-earl-co** [comment]
@mtthidoteu No, that is the entirety of the logs from the moment that `docker compose up -d` kicks off; I thought there would be more, as well! Does it have something to do with my having disabled remote connections to Plex in the web settings? I don't think so, since I can still query and access via the `plexapi` Python module. Any advice you have would be appreciated.
