### ISSUE TITLE
Option to disable wizarr account login for scenarios where another authentication method is being used already

### ISSUE THREAD

**Issue by mogno-jelly** [Wizarrrr/wizarr#8]
Hello, I was wondering if someone can opt out of using/creating a wizarr account during initial setup.  I am using Authelia to manage authentication and it would be nice to be able to opt out of the wizarr login prompt so I don't have to log in twice (one for Authelia and another for the wizarr).  I do understand that this can be a potential security issue for some, but maybe you can enforce initial wizarr creation, but give the ability to opt out afterwards for people who are using another form of authentication.

**Comment by mtthidoteu** [comment]
Why don't you setup Forward Auth? You can make it so Authelia automatically logs in to Wizarr. I intentionally added Http Auth for this very use case!

**Comment by mogno-jelly** [comment]
I'm still a noob but I will give this a go - ty!

**Comment by mogno-jelly** [comment]
> Why don't you setup Forward Auth? You can make it so Authelia automatically logs in to Wizarr. I intentionally added Http Auth for this very use case!

While I'm flailing, would you be able to point me on where this change needs to be done? I'm using NGINX Proxy Manager alongside Authelia on Unraid.  Thank you in advance!

**Comment by mogno-jelly** [comment]
Ended up adding this in my NGINX Proxy Manager config for wizarr:

proxy_set_header  Authorization "Basic [base64encoded username and pw]";
proxy_pass_header Authorization;

**Comment by mtthidoteu** [comment]
I've just updated and replace httpauth with a forms login BUT I have also made it so you can bypass it, so you can carry on using SSO! Make sure to whitelist the proper paths though!
