### ISSUE TITLE
[BUG] Error 500 after jellyfin user creation

### ISSUE THREAD

**Issue by patrick-mota** [Wizarrrr/wizarr#86]
**Describe the bug**
I use the latest version of wizarr with the docker-compose provided in the docs.

After generating an invitation code for my jellyfin, I try to use it.

I can fill all the fields with user/pass etc. then when I submit the form it redirects me to mydomain/setup/jellyfin and shows an error (see attached screenshot)

When I click on Users in the admin panel I got an infinite loop with the following error:

"An error occurred. Please try again later."

I don't know if it's related.

I tried to restart the container, the configuration is persisted (I see the invites in invitation tab) so it's probably not related to the data not persisted.

One last check I did is in jellyfin and the users are correctly created.

**Screenshots**
![image](https://user-images.githubusercontent.com/4503898/221850726-7257a6b0-afce-41bd-a588-2c4a78e214dd.png)

**Logs**
```
2023-02-28 13:01:01,741 - ERROR - Exception on /setup/jellyfin [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/app/jellyfin.py", line 155, in join_jellyfin
    jf_inviteUser(username, password, code, email)
  File "/data/app/jellyfin.py", line 60, in jf_inviteUser
    policy = dict(Get(f"/Users/{user_id}").json()["Policy"])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-02-28 13:01:01,742 - ERROR - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.```

**Additional context**
Add any other context about the problem here.

**Comment by patrick-mota** [comment]
More details:
I have my jellyfin configured in https via a cloudflared tunnel.

I can connect to my jellyfin instance but I can't stream anything.

If I try with the http url it works (can connect & stream).

In wizarr, if I configure the jellyfin url with https, I can save it and the problem I described in this topic appear but maybe isn't related to wizarr but more to jellyfin.

But if I try to configure the jellyfin url with http, I can't save it (even if wizarr discovers librarys when I click to discover).

If you think it's not related to jellyfin feel free to close the issue.

**Comment by mtthidoteu** [comment]
It sounds like Jellyfin isn't responding with the usual response it should be when updating the users, any idea why this could be?

**Comment by patrick-mota** [comment]
I have no idea what you expect to receive or how jellyfin should act but this is what I have in jellyfin log right after clicking on create account in wizarr invitation:

![image](https://user-images.githubusercontent.com/4503898/221859830-3e8b8ef9-6118-4dcb-b8d7-6293074bdb3b.png)

**Comment by mtthidoteu** [comment]
> Thank you for your answer, I have no idea what you expect to receive or how jellyfin should act but this is what I have in jellyfin log right after clicking on create account in wizarr invitation:
> 
> ![image](https://user-images.githubusercontent.com/4503898/221859830-3e8b8ef9-6118-4dcb-b8d7-6293074bdb3b.png)

This is strange, Jellyfin's log is contracting itself, it is showing the url as "/Users/{ID}" and then saying the id is empty... 
Are you on a dev/beta version of Jellyfin? I can't replicate it :/

**Comment by mtthidoteu** [comment]
Okay it looks like the User ID is empty, does it say anything above that about a POST request to create a user? (in the Jellyfin logs)

**Comment by patrick-mota** [comment]
No I don't have nothing else in logs.

In admin panel activity I have this:

"L'utilisateur okok a été créé"

Then:

"Le mot de passe pour l'utilisateur okok a été modifié"


Which means, the user okok was created and the password for the user okok has been modified.

I'll take a look later if I have to change the log level or something to get more informations in jellyfin.
