### ISSUE TITLE
[BUG] [UI] Change Request Instance field to a drop-down menu

### ISSUE THREAD

**Issue by strenkml** [Wizarrrr/wizarr#88]
**Describe the bug**
Currently the Request instance field in the settings is a text field. This should be changed to be a drop-down menu like the Server field uses.

**Screenshots**
![Request Instance Field](https://i.imgur.com/hKNj8iX.png)

**Comment by tuxx** [comment]
In this field you add the ombi/overseerr URL. So a dropdown would not be a good solution. Maybe a little clarification in the text above the input field would help clarify things?

**Comment by strenkml** [comment]
Ohhh that would make sense. Yeah some clarification in the label would help with that.
