### ISSUE TITLE
Feature Request - Add emby support

### ISSUE THREAD

**Issue by RenMu-V** [Wizarrrr/wizarr#93]
Please tell me when emby will be supported, I am a heavy user of emby, I experimented with your project, I found that it is feasible to replace emby with jellyfin, but I can't create an account properly, the problems are as follows: 1 the media library created and assigned can't be assigned correctly, 2 the password created for the user and the registration are not the same, so I can't login.
I hope emby will be added soon.

Also thank you very much for your dedication and contributors~

**Comment by mtthidoteu** [comment]
Emby should be supported, have you tried? It uses the same API so I don't see why it wouldn't work :)

**Comment by huluohu** [comment]
> Emby should be supported, have you tried? It uses the same API so I don't see why it wouldn't work :)

I tried on Emby and Wizarr was able to create an invitation account for me, but I couldn't log in using the account I created.

like this:

<img width="373" alt="image" src="https://github.com/wizarrrr/wizarr/assets/7138642/441149ec-049a-47d1-b0f4-6722be822362">
