### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by LeendertPlas** [Wizarrrr/wizarr#94]
**Describe the bug**
I tried to setup the tool using docker desktop, but when complete the initial stage to enter a password and username, the program is unable to find my plex server. I know for certain that my link and plex token are correct as i got it from other programs that already use that same information. I then also tried to do each combination of localhost, 127.0.0.1, local ip, external ip etc with the token plex reports for that link but nothing is working

**Logs**
The menu itself says this:
Error: Please Check Your Server URL and Token

There aren't any logs at all. but the path variable seems very strange:
/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**Comment by perfectly-preserved-pie** [comment]
@LeendertPlas I'm having the exact same issue, how did you resolve yours?

**Comment by cazrax** [comment]
I am currently having the same issue. Am running it in a docker on UnRaid and no URL will work even thought the token is correct.
