### ISSUE TITLE
[Feature Request] : Increase the code length

### ISSUE THREAD

**Issue by c11umw** [Wizarrrr/wizarr#99]
As per the title, the 6 chars are a little short - esp for a custom code you may create.

Being able to select a custom number of chars would be really useful for personal invites as well as making invites more secure by being harder to guess.

**Comment by mtthidoteu** [comment]
> As per the title, the 6 chars are a little short - esp for a custom code you may create.
> 
> Being able to select a custom number of chars would be really useful for personal invites as well as making invites more secure by being harder to guess.

Regarding security, I don't think there is really an issue, there are over 56,800,235,584 different possibilities for a string to be guessed! I don't think you'll be running out of strings anytime soon ahaha!

I don't think having the option to change the length would be very friendly, and it keeps the url nice and short as it is now. So I don't think I am planning on changing this anytime soon
